### ISSUE TITLE
[Feature] 지역 관련 처리 및 기능 추가

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#18]
### 요약
- 지역 관련 처리 및 기능 추가

### TODO 리스트
- [x] 특별시/도, 시/군/구, 읍/면/동, 리, 위도, 경도 데이터셋 구축
- [x] 서버 구동 시 데이터베이스로 지역 데이터셋 삽입하는 스크립트 및 환경 구축
- [x] 지역 관련 간단 기능 구현 (repository, entity, 필요 시 service, controller)
- [x] 테스트 코드 작성
