### ISSUE TITLE
[Feature] 회원 가입 기능 구현 및 Front End 병합 작업

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#55]
### 요약
회원 가입 기능 구현 및 간단한 Front End 코드 병합

### TODO 리스트
- [x] 약관 동의 페이지 구현
- [x] 사용자 정보 입력 페이지 구현
- [x] 선수 정보 입력 페이지 구혀
