### ISSUE TITLE
[Feature] 팀 관련 기능 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#59]
### 요약
 - 팀 관련 기능 구현

### TODO 리스트
- [x] 팀 생성 페이지 및 로직 구현
- [x] 팀 목록 페이지 및 로직 구현
- [x] 팀 모집 정보 페이지 및 로직 구현
- [x] 팀 상세 정보 페이지 및 로직 구현
