### ISSUE TITLE
[Feature] 네비게이션 바, 회원가입 플로우 UI, 페이징 등의 Layout fragment 처리

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#61]
### 요약
네비게이션 바, 회원가입 플로우 UI, 페이징 등의 Layout fragment 처리

### TODO 리스트
- [x] 네이게이션 바 클릭 시 클릭한 요소 hover 옵션 상시 활성화
- [x] 회원 가입 플로우 UI 적용
- [x] 페이징 처리 (layout 구현)
