### ISSUE TITLE
[Feature] 경기 기능 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#63]
### 요약
경기 관련 페이지 및 기능 구현

### TODO 리스트
- [x] 네비게이션 메뉴에 "경기"칸 추가
- [x] 경기 조회 페이지 및 기능 구현
- [x] 경기 상세 조회 페이지 및 기능 구현
- [x] 경기 참여 기능 구현
- [ ] 경기 종료 후 처리 구현 (설계 필요)

**Comment by JuhyunPark1831** [comment]
경기 종료 후 처리 기능 추후 구현
