### ISSUE TITLE
[Fix] 디버깅 및 테스트

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#65]
### 요약
 - 배포 작업을 위한 고도화 작업

### TODO 리스트
- [x] 부분 replace 하는 컨트롤러의 에러 처리
- [x] 에러 페이지 구현 및 페이지 반환하는 컨트롤러의 에러 처리
- [x] 없는 URL에 대하여 처리 방식 설계 및 구현
- [x] 이미 로그인 중일 때 로그인 페이지 접근에 대한 처리
- [x] location.href에서 에러 발생 시 처리
- [x] 페이징에서 요소 없을 때 빈 객체 처리
- [x] 현재까지 구현한 기능 테스트 및 각각의 에러 처리
- [x] api 주소 정리 및 코드 컨벤션 확립
