### ISSUE TITLE
[Feature] 마이 페이지 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#75]
### 요약
[여기에 기능 요청의 간단한 요약을 작성하세요.]

### TODO 리스트
- [x] 마이 페이지 구현
- [x] 경기 기록 조회 구현
- [x] 소속 팀 조회 구현
- [x] 마이 페이지 기능 구현
- [ ] userList 보여주는 부분에 연결 (자신의 마이페이지와 타인의 마이페이지 다르게 구현)

**Comment by JuhyunPark1831** [comment]
userList 보여주는 부분에 연결 추후 구현
