### ISSUE TITLE
[Feature] 반응형 UI 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#88]
### 요약
- 현재 구현한 모든 페이지의 반응형 UI 구현

### TODO 리스트
- [x] 헤더, 회원 가입 플로우 UI, 좌측 메뉴 UI 등의 fragment의 반응형 UI 구현
- [x] 로그인 / 메인 / 에러 / 추후 오픈 예정 페이지 반응형 UI 구현
- [x] 회원 가입 페이지 반응형 UI 구현
- [x] 팀 관련 페이지 반응형 UI 구현
- [x] 경기 관련 페이지 반응형 UI 구현
- [x] 마이 페이지 관련 페이지 반응형 UI 구현
