### ISSUE TITLE
[Fix] 반응형 UI 관련 수정 및 이메일 비밀번호 찾기 구현

### ISSUE THREAD

**Issue by JuhyunPark1831** [DribbleMatch/back-end#91]
### 요약
 - 반응형 UI 관련 수정
 - 이메일 비밀번호 찾기 구현

### TODO 리스트
- [x] 글씨체 수정 (font 및 굵기)
- [x] 미설정한 폰트 색 설정
- [x] 기타 어색한 부분 수정
- [x] 이메일 비밀번호 찾기 구현
